### ISSUE TITLE
capitalize() works as unexpected

### ISSUE THREAD

**Issue by MurWade** [jprichardson/string.js#137] opened 2015-03-27 23:26 UTC
`S('this post').capitalize().camelize().s; // returns ThisPost`
But
`S('this post').camelize().capitalize().s; // returns Thispost`

capitalize() IMO should only change the first character and not worry about the rest.

**Comment by az7arul** [comment] 2015-03-28 09:10
This seems to be the expected behavior. Both python and ruby return 

```ruby
'thisPost'.capitalize()
"Thispost"
```

**Comment by jprichardson** [comment] 2015-03-28 09:22
@MurWade notice the order of your two snippets... in the first you're doing `capitalize` first and then `camelize`, but on the second you're switching the order. You can see that only the first character is indeed capitalized: https://github.com/jprichardson/string.js/blob/3.1.1/lib/string.js#L86

But the question remains, should we be lower casing the rest of the string or leave it alone?

**Comment by MurWade** [comment] 2015-03-28 10:11
@jprichardson  exactly. i think it would make sense to leave the rest of the chars the way it is.

**Comment by az7arul** [comment] 2015-03-28 10:57
I don't think it makes sense to leave the rest alonse since most language define `capitalize` as a method that uppercases first character and downcases rest.

**Comment by jprichardson** [comment] 2015-03-28 11:09
@az7arul I'm good with that. Since that's the current behavior and Ruby/Python seem to follow that behavior, let's leave it as is then. @MurWade Closing. If I missed something in my understanding, let me know.

**Closed by jprichardson** 2015-03-28 11:09 UTC
